import { Match } from "@/lib/types";

export const demoMatches: Match[] = [
  {
    id: 26061101,
    stage: "그룹 스테이지",
    group: "A조",
    kickoff: "2026-06-12T04:00:00+09:00",
    venue: "Estadio Azteca, Mexico City",
    status: "LIVE",
    elapsed: 67,
    home: { id: 1, name: "Mexico", code: "MEX" },
    away: { id: 2, name: "South Africa", code: "RSA" },
    homeScore: 1,
    awayScore: 0,
    crowd: {
      home: 54,
      draw: 27,
      away: 19,
      predictions: 4281,
      poolPoints: 428100,
    },
  },
  {
    id: 26061202,
    stage: "그룹 스테이지",
    group: "H조",
    kickoff: "2026-06-12T20:00:00+09:00",
    venue: "BC Place, Vancouver",
    status: "UPCOMING",
    home: { id: 3, name: "Korea Republic", code: "KOR" },
    away: { id: 4, name: "Denmark", code: "DEN" },
    homeScore: null,
    awayScore: null,
    crowd: {
      home: 48,
      draw: 29,
      away: 23,
      predictions: 3814,
      poolPoints: 381400,
    },
  },
  {
    id: 26061303,
    stage: "그룹 스테이지",
    group: "J조",
    kickoff: "2026-06-13T07:00:00+09:00",
    venue: "MetLife Stadium, New York/New Jersey",
    status: "UPCOMING",
    home: { id: 5, name: "Argentina", code: "ARG" },
    away: { id: 6, name: "Algeria", code: "ALG" },
    homeScore: null,
    awayScore: null,
    crowd: {
      home: 68,
      draw: 20,
      away: 12,
      predictions: 5122,
      poolPoints: 512200,
    },
  },
  {
    id: 26061304,
    stage: "그룹 스테이지",
    group: "B조",
    kickoff: "2026-06-13T10:00:00+09:00",
    venue: "SoFi Stadium, Los Angeles",
    status: "UPCOMING",
    home: { id: 7, name: "Spain", code: "ESP" },
    away: { id: 8, name: "Cape Verde", code: "CPV" },
    homeScore: null,
    awayScore: null,
    crowd: {
      home: 72,
      draw: 18,
      away: 10,
      predictions: 2930,
      poolPoints: 293000,
    },
  },
  {
    id: 26061405,
    stage: "그룹 스테이지",
    group: "F조",
    kickoff: "2026-06-14T04:00:00+09:00",
    venue: "BMO Field, Toronto",
    status: "UPCOMING",
    home: { id: 9, name: "Canada", code: "CAN" },
    away: { id: 10, name: "Switzerland", code: "SUI" },
    homeScore: null,
    awayScore: null,
    crowd: {
      home: 39,
      draw: 31,
      away: 30,
      predictions: 2251,
      poolPoints: 225100,
    },
  },
];
